services:
  mysql:
    ports:
      - "127.0.0.1:3306:3306" # Exposing MySQL port to host

  redis:
    ports:
      - "127.0.0.1:6379:6379" # Exposing Redis port to host

  clickhouse:
    ports:
      - "127.0.0.1:8123:8123" # Exposing ClickHouse HTTP port to host
      - "127.0.0.1:9000:9000" # Exposing ClickHouse Native Protocol port to host

  backend:
    ports:
      - "127.0.0.1:8080:8080" # Exposing backend HTTP port to host
      - "127.0.0.1:3003:3003" # Exposing additional backend port to host

  frontend:
    ports:
      - "127.0.0.1:5173:5173" # Exposing frontend dev server port to host
